#!/bin/bash

# Scale the Django app deployment to 3 replicas
kubectl scale deployment messaging-app --replicas=3

# Verify that multiple pods are running
kubectl get pods

# Perform load testing on your app using wrk
# the app is running via minikube on port 59983
wrk -t12 -c400 -d30s http://127.0.0.1:59983

# Monitor Resource Usage
kubectl top pods
